### ISSUE TITLE
Cant See any Custom_Components

### ISSUE THREAD

**Issue by mokshmridul** [custom-cards/tracker-card#21]
Hey Guys,
I have configured the card with the following items:

Configuration.yaml

```#Custom Components Updater
custom_updater:
  show_installable: False
  hide_sensor: false
  track:
    - components
    - cards
    - python_scripts
```

ui-lovelace.yaml

```resources:
  - url: /local/gauge-card.js?v=0.2.0
    type: js
  - url: /local/weather-card.js
    type: js
  - url: /local/state-attribute-element.js?v=0.1.0
    type: js
  - url: /local/text-element.js?v=0.0.2
    type: js
  - url: /local/monster-card.js?v=0.2.3
    type: js
    resources:
  - url: /local/tracker-card.js?v=0.1.5
    type: js
```

```    - type: custom:tracker-card
      title: 'Custom Cards Tracker'
      trackers:
        - sensor.custom_card_tracker
        - sensor.custom_component_tracker
```

However, under the card, I am not being able to see any components under the "custom_components" part (image below).

![capture](https://user-images.githubusercontent.com/8089422/46256754-89425b80-c4cc-11e8-9028-86190246b28a.JPG)

**Comment by ludeeus** [comment]
Do you see the sensor for it in /dev-states?

**Comment by ludeeus** [comment]
Also you can remove some of your config (default values/not in use)
```yaml
custom_updater:
  track:
    - components
    - cards
```

**Comment by mokshmridul** [comment]
> Do you see the sensor for it in /dev-states?

I can see the entity, but it has not attributes (picture below)
![2](https://user-images.githubusercontent.com/8089422/46256801-4b920280-c4cd-11e8-8a0d-2b303376ab04.JPG)

**Comment by mokshmridul** [comment]
> Also you can remove some of your config (default values/not in use)
> 
> ```yaml
> custom_updater:
>   track:
>     - components
>     - cards
> ```

If i remove these parts, then the whole box goes blank

![3](https://user-images.githubusercontent.com/8089422/46256811-87c56300-c4cd-11e8-8b99-3f978224972e.JPG)

**Comment by ludeeus** [comment]
If the sensor has no attributes, that is a sign of network issue, try "CHECK".
That image are missing headers to, see if the component failed to setup.

**Comment by mokshmridul** [comment]
Im sorry, but what does try "CHECK" mean? and how do i go about it?

The components dont seem to have any errors in the logs.

**Comment by ludeeus** [comment]
nvm.... since you posted an image of that button I though it made sense..
But run the service `custom_updater.check_all` it does the same thing

**Comment by mokshmridul** [comment]
so where do we go from here?

**Comment by ludeeus** [comment]
run the service `custom_updater.check_all` or restart

**Comment by mokshmridul** [comment]
im getting an error if i run that
```Error executing service <ServiceCall custom_updater.check_all (c:5fb7834a43a348d691481c0dc0265ecf)>
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1185, in _event_to_service_call
    await self._hass.async_add_executor_job(execute_service)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/homeassistant/lib/python3.6/site-packages/homeassistant/core.py", line 1182, in execute_service
    service_handler.func(service_call)
  File "/home/homeassistant/.homeassistant/custom_components/custom_updater.py", line 85, in check_all_service
    card_controller.cache_versions()
NameError: free variable 'card_controller' referenced before assignment in enclosing scope
```

Restart does not solve the issue

**Comment by ludeeus** [comment]
Then it failed setting up, try restart

**Comment by mokshmridul** [comment]
I did restart HA, but the issue persists through reboots.

**Comment by ludeeus** [comment]
I'm unable to replicate that.
But until you have attributes in the sensors (and the sensors exist) the card will not show anything.
You can try adding `show_installable: True`

**Comment by mokshmridul** [comment]
The sensors do exist as far as i understand.

Adding `show_installable: True` does the following

![4](https://user-images.githubusercontent.com/8089422/46257084-85fd9e80-c4d1-11e8-8f4e-af8d95f24a87.JPG)

**Comment by mokshmridul** [comment]
It seems that the sensors are not showing up, even though they are installed (tautulli, authentciated, custom updater)

Any clue what the issue could be?

**Comment by ludeeus** [comment]
It can not get the local file version.
to get this it reads the file looking for `__version__`

**Comment by mokshmridul** [comment]
> It can not get the local file version.
> to get this it reads the file looking for `__version__`

The file has the required version number in it. I can see it when i manually open the file. 

Im quite stuck at the moment, as it was working fine till yesterday, and nothing has been updated since then

**Comment by ludeeus** [comment]
I see by the functions that at least this version are correct...
What HW are you using?

**Comment by mokshmridul** [comment]
Im running it on an ubuntu 18.04 vm server

Do you think its a HW issue?

**Comment by ludeeus** [comment]
It could be an OS issue if you where using OSX or Windows, but ubuntu should work.

**Comment by mokshmridul** [comment]
I dont know, but im probably doing something wrong, just need to figure out what that is :/

**Comment by ludeeus** [comment]
Agreed, you figure out this one and I relax :D

**Comment by mokshmridul** [comment]
> Agreed, you figure out this one and I relax :D

haha, you have helped a lot. Im gonna try this one out, but do be prepared to step back into the ring when i goof up :)

**Comment by ludeeus** [comment]
Try changing:

```
REQUIREMENTS = ['pyupdate==0.1.2']
```
to:
```
REQUIREMENTS = ['pyupdate==0.1.3']
```
in custom_updater.py

**NOTE!: IF ANYONE ESLE SEE THIS, DO NOT DO THIS!**

**Comment by mokshmridul** [comment]
> Try changing:
> 
> ```
> REQUIREMENTS = ['pyupdate==0.1.2']
> ```
> to:
> 
> ```
> REQUIREMENTS = ['pyupdate==0.1.3']
> ```
> in custom_updater.py
> 
> **NOTE!: IF ANYONE ESLE SEE THIS, DO NOT DO THIS!**

Changed it, saved the file, and rebooted, but no effect

**Comment by ludeeus** [comment]
Then you have something seriously wrong in your setup.
That version of `pyupdate` uses the exact same method of fetching local versions as the old `custom_updater`
_I copied the old code_

**Comment by mokshmridul** [comment]
> sion of `pyupdate` uses the exact same method of fetching local versions as the old `custom_u`

I changed it to `0.1.1` and now im getting components which are not even on my setup

![12](https://user-images.githubusercontent.com/8089422/46260986-e957f280-c50a-11e8-90cf-4ff533f96abc.JPG)

**Comment by ludeeus** [comment]
0.1.1 did not have "hide elements without a remote version"

**Comment by mokshmridul** [comment]
do you think i should try pip install pyupdate?

Edit: updating (in the venv) pydate to 0.1.3 did not help

**Comment by ludeeus** [comment]
That will not help, that is basically the same as the change you did in the file :/

**Comment by sendorm** [comment]
I seem to have the same issue. It happened after updating custom_updater to 3.1.0. Hass in on raspberry pi with version 0.79.0.

**Comment by Ton1965** [comment]
Same about me. I have lost any information about custom elements:

![image](https://user-images.githubusercontent.com/40115682/46295403-a6e0f500-c5a0-11e8-8614-432e45e974d9.png)

I did several updates at that time so I am not sure which one in particular is a reason. I have updated tracker-card itself, custom_updater and HA to 0.79.1. My gut feeling is that custom_updater is the culprit but I cannot prove it. :-)

**Comment by ludeeus** [comment]
@Ton1965 You do not have the latest card (v 0.1.5).
To check if the component is the issue add `show_installable: true` to the config of it

**Comment by bastshoes** [comment]
Have same issue after update to 0.79.2

**Comment by mokshmridul** [comment]
Looks like a number of us are having the same issue. Has anyone managed to figure out the issue?

**Comment by ludeeus** [comment]
Yes and no, I didn't, but @pnbruckner did in https://github.com/custom-components/custom_updater/issues/37
I''m working on that now.

**Comment by mokshmridul** [comment]
> Yes and no, I didn't, but @pnbruckner did in [custom-components/custom_updater#37](https://github.com/custom-components/custom_updater/issues/37)
> I''m working on that now.

That sounds awesome mate. Thanks to you and @pnbruckner

**Comment by ludeeus** [comment]
`custom_updater` version 3.1.1 fixes this.
<https://github.com/custom-components/custom_updater/releases/tag/3.1.1>

I have verified this on hassio and hassbian.

**Comment by ludeeus** [comment]
@mokshmridul @sendorm @Ton1965 @bastshoes Can you test that version on your systems as well?

**Comment by mokshmridul** [comment]
> @mokshmridul @sendorm @Ton1965 @bastshoes Can you test that version on your systems as well?

Yes, just tried 3.1.1 and the issue is resolved. If its fixed for everyone, we can close this thread.

Thanks @ludeeus

**Comment by sendorm** [comment]
After the 3.1.1 update, custom_updater is visible and it works as expected (can update cards). But my aftership component is still not visible.

**Comment by ludeeus** [comment]
@sendorm can you hastebin the content of that aftership file?

**Comment by sendorm** [comment]
I’ll do it as soon as I get home.

**Comment by sendorm** [comment]
the content is here:
https://hastebin.com/yaponefumi.coffeescript
This is the github page for the component and card:
https://github.com/tr1plus/ha-aftership

**Comment by ludeeus** [comment]
Sorry @sendorm that will not go.
You can tips the developer about this: <https://github.com/custom-components/custom_updater/wiki/cards> to get it working

**Comment by sendorm** [comment]
Ok I'll inform the developer. Thank you.

**Comment by jjanderson** [comment]
Hi, I am also experiencing this problem. I am running HASSOS on NUC.

I have a number of custom components, including alexa_media, average_temperature, feedparser, huesensor, however in Lovelace, I can only see the custom cards... this is my config in the tracker card:

```
  - type: 'custom:tracker-card'
    trackers:
      - sensor.custom_card_tracker
      - sensor.custom_component_tracker
```

In terms of my config.yaml, I have this:

```
custom_updater:
  show_installable: true
  track:
    - cards
    - components
    - python_scripts
  component_urls:
# Released build
    - https://raw.githubusercontent.com/keatontaylor/custom_components/master/custom_components.json
    - https://raw.githubusercontent.com/ljmerza/calendar-card/master/custom_updater.json
    - https://raw.githubusercontent.com/ljmerza/light-entity-card/master/custom_updater.json
    - https://raw.githubusercontent.com/kalkih/mini-graph-card/master/tracker.json
    - https://raw.githubusercontent.com/robmarkcole/Hue-sensors-HASS/master/custom_updater.json
    - https://raw.githubusercontent.com/keatontaylor/alexa_media_player/master/custom_components.json
    - https://raw.githubusercontent.com/Limych/HomeAssistantComponents/master/custom_components.json
```

Can you help? 

Thanks

**Comment by ludeeus** [comment]
Open a separate issue and fill out the template
